# Generated by Django 3.1.3 on 2020-11-24 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0003_auto_20201124_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TextField(default='12:00'),
        ),
    ]
