# Generated by Django 3.1.3 on 2020-12-01 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0006_auto_20201124_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='participants',
        ),
    ]
